develop_topic_strategy:
  description: >
    基于内容分析结果和业务目标，制定精准的选题策略：
    
    1. **热门选题挖掘**：
       - 分析成功案例中的热门选题模式和规律
       - 识别与目标产品/服务相关的趋势性话题
       - 挖掘具有长期价值的常青选题方向
    
    2. **关键词策略分析**：
       - 构建核心关键词集群和语义网络
       - 分析关键词竞争度和搜索热度
       - 制定关键词布局和SEO优化策略
    
    3. **竞争环境分析**：
       - 研究同类产品/服务的选题策略
       - 识别市场空白和差异化机会
       - 分析竞争对手的内容表现和用户反馈
    
    4. **选题公式制定**：
       - 提炼可复制的选题模板和公式
       - 设计不同类型内容的选题框架
       - 建立选题评估和筛选机制
    
    **输入数据**：
    - 业务背景: {business_context}
    - 目标产品: {target_product}
    - 分析报告: {analysis_report}
    - 成功案例: {success_cases}
    
    **输出要求**：
    - 提供具体可执行的选题策略
    - 包含至少20个具体选题建议
    - 给出选题优先级和时间规划
    - 制定选题效果评估机制

  expected_output: >
    返回一个详细的选题策略JSON对象，包含：
    - business_domain: 业务领域定位
    - target_product: 目标产品描述
    - trending_topics: 热门选题列表(至少15个)
    - evergreen_topics: 常青选题列表(至少10个)
    - seasonal_topics: 季节性选题分类
    - topic_formulas: 选题公式模板(至少5个)
    - keyword_clusters: 关键词集群字典
    - competition_analysis: 竞争分析结果
    - pain_point_topics: 痛点类选题(至少8个)
    - solution_topics: 解决方案类选题(至少8个)
    - inspiration_topics: 灵感启发类选题(至少6个)
    - tutorial_topics: 教程干货类选题(至少8个)

  agent: topic_strategy_expert

analyze_target_audience:
  description: >
    深度分析目标用户画像，制定精准的TA策略：
    
    1. **用户画像构建**：
       - 基于成功案例分析目标用户特征
       - 构建详细的用户画像和行为模式
       - 识别主要和次要用户群体
    
    2. **需求痛点分析**：
       - 挖掘用户核心需求和潜在痛点
       - 分析用户决策过程和影响因素
       - 识别用户行为驱动机制
    
    3. **触达策略设计**：
       - 制定用户触达和沟通策略
       - 设计用户旅程和互动节点
       - 规划用户转化漏斗和关键路径
    
    4. **内容偏好分析**：
       - 分析目标用户的内容消费习惯
       - 识别用户互动和分享行为模式
       - 制定内容适配和个性化策略
    
    **输入数据**：
    - 业务背景: {business_context}
    - 目标产品: {target_product}
    - 用户数据: {user_insights}
    - 行为分析: {behavior_analysis}
    
    **输出要求**：
    - 提供详细的用户画像和特征分析
    - 制定具体的触达和转化策略
    - 给出内容偏好和互动建议
    - 设计用户体验优化方案

  expected_output: >
    返回一个详细的TA策略JSON对象，包含：
    - primary_persona: 主要用户画像字典
    - secondary_personas: 次要用户画像列表
    - demographics: 人口统计学特征
    - psychographics: 心理特征分析
    - behavioral_patterns: 行为模式列表
    - core_needs: 核心需求列表
    - pain_points: 用户痛点列表
    - motivations: 驱动因素列表
    - content_preferences: 内容偏好字典
    - engagement_triggers: 互动触发器列表
    - conversion_points: 转化节点列表

  agent: target_audience_analyst

create_content_creation_guide:
  description: >
    制定全方位的内容创作指导，包括文案、配图、视频三个维度：
    
    1. **文案创作指南**：
       - 制定标题创作模板和关键词策略
       - 设计开头钩子和正文结构框架
       - 提供CTA设计和互动引导技巧
    
    2. **配图设计指南**：
       - 分析成功案例的视觉风格和色彩方案
       - 提供构图规则和拍摄技巧指导
       - 制定品牌一致性和视觉识别规范
    
    3. **视频脚本指南**：
       - 设计视频脚本模板和场景规划
       - 提供镜头语言和剪辑节奏建议
       - 制定视频制作标准和质量要求
    
    4. **创作流程标准化**：
       - 建立内容创作的标准化工作流程
       - 设计质量检查清单和评估体系
       - 制定内容优化和迭代机制
    
    **输入数据**：
    - 分析报告: {content_analysis}
    - 成功要素: {success_factors}
    - 视觉分析: {visual_insights}
    - 创作需求: {creation_requirements}
    
    **输出要求**：
    - 提供可操作的创作指导和模板
    - 包含具体的技巧建议和示例
    - 制定标准化的创作流程
    - 设计质量评估和优化机制

  expected_output: >
    返回一个详细的内容创作指南JSON对象，包含：
    - copywriting_guide: 文案创作指南
      * title_templates: 标题模板列表
      * opening_hooks: 开头钩子列表
      * content_frameworks: 正文框架列表
      * cta_templates: CTA模板列表
      * tone_guidelines: 语调指南字典
    - visual_guide: 配图创作指南
      * style_direction: 整体风格方向
      * color_palette: 配色方案列表
      * composition_rules: 构图规则列表
      * shooting_tips: 拍摄技巧列表
    - video_script_guide: 视频脚本指南
      * script_templates: 脚本模板列表
      * scene_breakdowns: 场景分解列表
      * shot_compositions: 镜头构图列表
      * duration_guidelines: 时长指南字典
    - creation_workflow: 创作工作流程列表
    - quality_checklist: 质量检查清单列表

  agent: content_creation_guide

