analyze_target_audience: 
  description: >
    深度分析目标用户画像，制定精准的TA策略：
    
    1. **用户画像构建**：
       - 基于成功案例分析目标用户特征
       - 构建详细的用户画像和行为模式
       - 识别主要和次要用户群体
    
    2. **需求痛点分析**：
       - 挖掘用户核心需求和潜在痛点
       - 分析用户决策过程和影响因素
       - 识别用户行为驱动机制
    
    3. **内容偏好分析**：
       - 分析目标用户的内容消费习惯
       - 识别用户互动和分享行为模式
       - 制定内容适配和个性化策略
    
    **输入数据**：
    - 业务背景: {business_context}
    - 目标产品: {target_product}
    - 业务目标: {business_goals}
    - 其他同类热门内容分析报告: {analysis_report}
    
    **说明**: LLM将从完整的内容分析报告中智能提取用户洞察、痛点、价值主张等信息
    
    **输出要求**：
    - 提供详细的用户画像和特征分析
    - 制定具体的触达和转化策略
    - 给出内容偏好和互动建议
    - 设计用户体验优化方案

  expected_output: >
    返回一个详细的TA策略JSON对象，包含：
    - primary_persona: 主要用户画像字典
    - secondary_personas: 次要用户画像列表
    - demographics: 人口统计学特征
    - psychographics: 心理特征分析
    - behavioral_patterns: 行为模式列表
    - core_needs: 核心需求列表
    - pain_points: 用户痛点列表
    - motivations: 驱动因素列表
    - content_preferences: 内容偏好字典
    - engagement_triggers: 互动触发器列表
    - conversion_points: 转化节点列表

  agent: target_audience_analyst

develop_topic_strategy:
  description: >
    基于目标用户分析结果，制定精准的选题策略。请严格参考前一步的目标用户分析结果，
    确保选题与用户需求、痛点和动机高度匹配：
    
    1. **业务领域聚焦**：
       - 明确定义业务领域和核心价值主张
       - 分析目标产品的差异化优势
       - 确定内容营销的核心目标
    
    2. **选题公式制定**：
       - 基于用户画像制定选题公式
       - 结合竞争分析识别差异化机会
       - 建立选题评估和筛选标准
    
    3. **精选选题推荐**：
       - 综合考虑用户需求、业务目标、竞争环境
       - 筛选出3-5个最有潜力的选题方向
       - 每个选题给出详细的评估理由和执行建议
    
    4. **竞争策略分析**：
       - 分析同类产品的选题策略
       - 识别市场空白和机会点
       - 制定差异化内容策略
    
    **输入数据**：
    - 目标用户分析结果: 通过context获取前一步的用户分析结果
    - 业务背景: {business_context}
    - 目标产品: {target_product}
    - 业务目标: {business_goals}
    - 其他同类热门内容分析报告: {analysis_report}
    
    **说明**: LLM将从完整的内容分析报告中智能提取成功案例、内容创作模式等信息
    
    **输出要求**：
    - 重点推荐3-5个高质量选题
    - 每个选题包含评估理由和执行建议
    - 提供可复制的选题公式
    - 制定优先级和时间规划

  expected_output: >
    返回一个聚焦的选题策略JSON对象，包含：
    - business_domain: 业务领域定位
    - target_product: 目标产品描述
    - recommended_topics: 精选推荐选题列表(3-5个)，每个包含：
      - title: 选题标题
      - rationale: 选择理由
      - target_audience: 目标用户群
      - expected_engagement: 预期互动效果
      - execution_difficulty: 执行难度评估
      - priority_score: 优先级评分(1-10)
    - topic_formulas: 选题公式模板(3-5个)
    - keyword_clusters: 核心关键词集群
    - competition_analysis: 竞争分析要点

  agent: topic_strategy_expert


create_content_creation_guide:
  description: >
    **【内容创作执行手册】**
    
    基于前面的用户分析和选题策略，为每个推荐选题提供完整的、可直接使用的创作素材包。
    
    **核心原则**：提供成品而非模板，让商家和内容运营能够拿来即用。
    
    **总体执行方向**：
    - 每个选题先说明其商业价值和用户需求匹配点
    - 再提供完整的执行素材（文案、脚本、配图描述）
    - 确保内容符合目标用户的语言习惯和消费偏好
    
    **具体执行要求**：
    
    1. **完整文案创作**（不是文案模板）：
       - 为每个选题提供3-5个完整的可发布文案
       - 包含吸引人的标题、引人入胜的开头、价值丰富的正文、明确的CTA结尾
       - 文案长度适合小红书平台，语调符合目标用户群体
       - 直接可复制粘贴发布，无需二次加工
    
    2. **详细视频脚本**（不是脚本指南）：
       - 人物设定：具体描述出镜人物的年龄、职业、穿着、性格特点
       - 完整时间轴：按秒标注每个时间段的动作、表情、台词
       - 场景描述：详细描述拍摄场景、道具、背景环境
       - 逐句台词：包含语调提示、停顿位置、情感表达
       - 镜头指导：特写、中景、全景的具体切换时机
    
    3. **精确配图描述**（不是拍摄技巧）：
       - 画面构成：前景、中景、背景的具体元素和位置
       - 人物细节：服装颜色、发型、表情、姿态、年龄特征
       - 环境描述：光线方向（自然光/暖光）、色调（清新/温暖/专业）、氛围感
       - 道具和装饰：具体的产品展示角度、生活场景布置
       - 可直接用于AI绘图工具或指导摄影师拍摄
    
    **输入数据**：
    - 目标用户分析结果: 通过context获取第一步的用户分析结果
    - 选题策略结果: 通过context获取第二步的选题策略结果
    - 业务背景: {business_context}
    - 业务目标: {business_goals}
    - 其他同类热门内容分析报告: {analysis_report}

    
    **说明**: LLM将从完整的内容分析报告中智能提取成功案例、视觉设计模式等信息
    
    **商业价值导向**：
    - 每个选题必须明确说明其商业价值和转化路径
    - 文案和脚本要直接服务于产品推广和用户转化  
    - 配图要突出产品特色和使用场景的真实感
    
    **质量标准**：
    - 文案可直接发布，无需修改
    - 视频脚本可直接指导拍摄，包含所有执行细节
    - 配图描述足够详细，设计师或AI工具可直接使用
    - 内容符合小红书平台调性和用户习惯

  expected_output: >
    返回一个内容创作执行手册JSON对象，包含完整的创作素材包：
    
    - topic_content_packages: 选题内容包列表，每个包含：
      * topic_title: 选题标题
      * business_value: 该选题的商业价值和转化逻辑
      * target_pain_point: 针对的用户痛点
      * complete_copywriting: 一个完整文案，包含：
        - complete_title: 完整标题（可直接使用）
        - full_content: 完整正文内容（开头+正文+结尾+CTA）
        - content_length: 字数统计
        - posting_time_suggestion: 建议发布时间
        - content_type: 内容形式（图文笔记/视频笔记）
      * video_script: 视频脚本（仅当content_type为视频笔记时提供），包含：
        - character_profile: 出镜人物详细设定（年龄、职业、穿着、性格）
        - timeline_script: 按秒标注的时间轴脚本
        - scene_description: 拍摄场景详细描述
        - dialogue_with_emotion: 逐句台词（含语调和情感提示）
        - camera_directions: 镜头切换指导
        - props_and_setup: 道具和布景要求
      * image_descriptions: 配图描述列表(3-5张)，每个包含：
        - image_purpose: 图片用途（首图/内容图/产品图）
        - composition_details: 画面构成详细描述
        - character_appearance: 人物外观详细描述
        - environment_setting: 环境和氛围描述
        - lighting_and_tone: 光线和色调要求
        - ai_prompt_ready: 可直接用于AI绘图的提示词
    
    - overall_execution_tips: 整体执行建议
      * content_quality_standards: 内容质量标准
      * platform_best_practices: 小红书平台最佳实践
      * engagement_optimization: 互动优化建议

  agent: content_creation_guide

